version: 2.1
jobs:
  test_classification_model:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.8.5
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: Running tests
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r /packages/classification_model/requirements.txt
            py.test -vv /packages/classification_model/tests

workflows:
  version: 2.1
  test-all:
    jobs:
      - test_classification_model






